# Generated by Django 4.1 on 2022-09-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_todo_date_itemtodolist_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtodolist',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
